/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/lib/utils/config/flatten.js TAP > all flat option keys 1`] = `
Array [
  "access",
  "all",
  "allowSameVersion",
  "alwaysAuth",
  "audit",
  "auditLevel",
  "before",
  "binLinks",
  "browser",
  "ca",
  "cache",
  "call",
  "cert",
  "ciName",
  "color",
  "commitHooks",
  "search",
  "diffIgnoreAllSpace",
  "diffNameOnly",
  "diffNoPrefix",
  "diffDstPrefix",
  "diffSrcPrefix",
  "diffText",
  "diffUnified",
  "dryRun",
  "engineStrict",
  "retry",
  "timeout",
  "force",
  "foregroundScripts",
  "formatPackageLock",
  "git",
  "gitTagVersion",
  "global",
  "globalStyle",
  "httpsProxy",
  "ifPresent",
  "ignoreScripts",
  "omit",
  "includeStaged",
  "key",
  "legacyBundling",
  "legacyPeerDeps",
  "localAddress",
  "maxSockets",
  "message",
  "nodeVersion",
  "noProxy",
  "npmVersion",
  "offline",
  "otp",
  "packageLock",
  "packageLockOnly",
  "parseable",
  "preferOffline",
  "preferOnline",
  "preid",
  "proxy",
  "rebuildBundle",
  "registry",
  "save",
  "saveBundle",
  "saveExact",
  "savePrefix",
  "projectScope",
  "scriptShell",
  "signGitCommit",
  "signGitTag",
  "strictPeerDeps",
  "strictSSL",
  "defaultTag",
  "tagVersionPrefix",
  "umask",
  "userAgent",
  "npmBin",
  "nodeBin",
  "hashAlgorithm",
]
`
